name: genova
channels:
  - pyg
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - blas=1.0
  - bottleneck=1.3.5
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2023.01.10
  - certifi=2022.12.7
  - cffi=1.15.1
  - charset-normalizer=2.0.4
  - cryptography=37.0.1
  - cudatoolkit=11.3.1
  - ffmpeg=4.3
  - fftw=3.3.9
  - freetype=2.11.0
  - giflib=5.2.1
  - gmp=6.2.1
  - gnutls=3.6.15
  - idna=3.3
  - intel-openmp=2021.4.0
  - jpeg=9e
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libdeflate=1.8
  - libffi=3.3
  - libgcc-ng=11.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libgomp=11.2.0
  - libiconv=1.16
  - libidn2=2.3.2
  - libpng=1.6.37
  - libstdcxx-ng=11.2.0
  - libtasn1=4.16.0
  - libtiff=4.4.0
  - libunistring=0.9.10
  - libwebp=1.2.2
  - libwebp-base=1.2.2
  - lz4-c=1.9.3
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - ncurses=6.3
  - nettle=3.7.3
  - numexpr=2.8.3
  - numpy=1.23.1
  - numpy-base=1.23.1
  - openh264=2.1.1
  - openssl=1.1.1s
  - packaging=21.3
  - pandas=1.4.3
  - pillow=9.2.0
  - pip=22.1.2
  - pooch=1.4.0
  - pycparser=2.21
  - pyopenssl=22.0.0
  - pyparsing=3.0.4
  - pysocks=1.7.1
  - python=3.9.12
  - python-dateutil=2.8.2
  - pytorch=1.12.1
  - pytorch-mutex=1.0
  - pytorch-scatter=2.1.0
  - pytorch-sparse=0.6.16
  - pytz=2022.1
  - readline=8.1.2
  - requests=2.28.1
  - scipy=1.10.0
  - setuptools=63.4.1
  - six=1.16.0
  - sqlite=3.39.2
  - tk=8.6.12
  - torchaudio=0.12.1
  - torchvision=0.13.1
  - typing_extensions=4.3.0
  - tzdata=2022a
  - urllib3=1.26.11
  - wheel=0.37.1
  - xz=5.2.5
  - zlib=1.2.12
  - zstd=1.5.2
  - pip:
      - antlr4-python3-runtime==4.9.3
      - appdirs==1.4.4
      - click==8.1.3
      - docker-pycreds==0.4.0
      - gitdb==4.0.10
      - gitpython==3.1.30
      - hydra-core==1.3.1
      - omegaconf==2.3.0
      - pathtools==0.1.2
      - protobuf==4.21.12
      - psutil==5.9.4
      - pyyaml==6.0
      - sentry-sdk==1.15.0
      - setproctitle==1.3.2
      - smmap==5.0.0
      - wandb==0.13.10
